import AnimatedText from "@/components/AnimatedText";
import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import React, { useEffect, useRef } from "react";
import profilePic from "../../public/images/profile/IGP8BGB.png";
import { useInView, useMotionValue, useSpring } from "framer-motion";
import Skills from "@/components/Skills";

const AnimatedNumbers = ({ value }) => {
  const ref = useRef(null);

  const motionValue = useMotionValue(0);
  const springValue = useSpring(motionValue, { duration: 3000 });
  const isInView = useInView(ref, { once: true });

  useEffect(() => {
    if (isInView) {
      motionValue.set(value);
    }
  }, [isInView, value, motionValue]);

  useEffect(() => {
    springValue.on("change", (latest) => {
      if (ref.current && latest.toFixed(0) <= value) {
        ref.current.textContent = latest.toFixed(0);
      }
    });
  }, [springValue, value]);

  return <span ref={ref}></span>;
};

const about = () => {
  return (
    <>
      <Head>
        <title>Diki Somantri | About Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex flex-col items-center justify-center">
        <Layout className="pt-16">
          <AnimatedText
            text="Passion is the Key to Success!"
            className="mb-16"
          />
          <div className="grid w-full grid-cols-8 gap-16">
            <div className="col-span-3 flex flex-col items-start justify-start">
              <h2 className="mb-4 text-lg font-bold uppercase text-dark text-dark/75">
                Biography
              </h2>
              <p className="font-medium">
                Hi, I'm Diki Somantri, A Bachelor's degree in Informatics
                Management from Piksi Ganesha Polytechnic, Bandung. Possessing
                basic proficiency in HTML, CSS, JavaScript,
                React.js,Next.js,Node.js,MongoDB, PHP, MySQL, Git, Laravel,
                Bootstrap Framework and currently attending a Full-Stack Web
                Developer bootcamp program to further enhance skills in web
                development. A meticulous individual eager for a full-time
                remote opportunity in Full-Stack Web Development or Back End
                Development.
              </p>
              <p className="my-4 font-medium">
                I believe that back-end development is more than just writing
                code – it's about solving complex problems and crafting
                seamless, efficient systems that enhance user experiences. With
                a focus on functionality and reliability, I strive to create
                backend solutions that empower users and drive business success.
                Let's collaborate to turn challenges into opportunities and
                build innovative digital experiences together.
              </p>
              <p className="font-medium">
                Regardless of project size or complexity, I bring unwavering
                dedication to technical excellence and user-centered
                development. With expertise in building reliable, efficient
                systems, I deliver high-quality solutions tailored to your
                business needs. My skills in scalable, secure backend
                architectures equip me to confidently overcome technical
                hurdles. Furthermore, I craft robust, flexible systems.
                Collaborating seamlessly with frontend and design teams, I
                prioritize creating engaging, user-friendly web applications.
                Excited to apply my skills to your project, let's create
                exceptional products together.
              </p>
            </div>
            <div className="col-span-3 relative h-max rounded-2xl border-2 border-solid border-dark bg-light p-4">
              <div className="absolute top-0 -right-3 -z-10 w-[102%] h-[103%] rounded-[2rem] bg-dark" />
              <Image
                src={profilePic}
                alt="Diki Somantri"
                className="w-full h-auto rounded-2xl"
              />
            </div>

            <div className="col-span-2 flex flex-col items-end justify-between">
              <div className="flex flex-col items-end justify-center">
                <span className="inline-block text-7xl font-bold">
                  <AnimatedNumbers value={3} />+
                </span>
                <h2 className="text-xl font-medium capitalize text-dark/75">
                  Satisfied Clients
                </h2>
              </div>
              <div className="flex flex-col items-end justify-center">
                <span className="inline-block text-7xl font-bold">
                  <AnimatedNumbers value={3} />+
                </span>
                <h2 className="text-xl font-medium capitalize text-dark/75">
                  Project Completed
                </h2>
              </div>
              <div className="flex flex-col items-end justify-center">
                <span className="inline-block text-7xl font-bold">
                  <AnimatedNumbers value={1} />+
                </span>
                <h2 className="text-xl font-medium capitalize text-dark/75">
                  Years of experience
                </h2>
              </div>
            </div>
          </div>
          <Skills />
        </Layout>
      </main>
    </>
  );
};

export default about;
